---
- name: Install guacamole and tomcat
  hosts: tag_Name_fresh_install
  become: true
  gather_facts: false

  tasks:
    - name: Install apt packages
      become: true
      apt:
          update_cache: true
          cache_valid_time: 3600
          pkg:
              - guacd
              - default-jdk

    - name: Ensure group "tomcat" exists
      ansible.builtin.group:
        name: tomcat
        state: present
        system: true

    - name: Add the user 'tomcat' with a specific uid and a primary group of 'tomcat'
      ansible.builtin.user:
        name: tomcat
        comment: tomcat
        uid: 1040
        group: tomcat
        home: /usr/share/tomcat
        shell: /bin/false

    - name: Create a tomcat directory if it does not exist
      ansible.builtin.file:
        path: /usr/share/tomcat
        state: directory
        mode: '0777'
        owner: ubuntu
        group: ubuntu

    - name: Copy tomcat files
      unarchive:
          src: tomcat.tar.gz
          dest: /usr/share/tomcat
          owner: tomcat
          group: tomcat
          mode: '777'

    - name: Change ownership of tomcat directory
      ansible.builtin.file:
        path: /usr/share/tomcat
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory

    - name: Copy tomcat service file
      copy:
          src: tomcat.service
          dest: /etc/systemd/system/
          owner: ubuntu
          group: ubuntu
          mode: '0664'

    - name: Enable service tomcat, and not touch the state
      ansible.builtin.service:
        name: tomcat.service
        enabled: yes
  
    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start service tomcat in all cases
      ansible.builtin.service:
         name: tomcat.service
         state: started