---
- name: Install and Configure Docker
  import_playbook: docker.yaml
- name: Install and Configure Gnome Remote Desktop and Guacamole
  import_playbook: grd.yaml
# - name: Cleanup image for AWS Marketplace
  # import_playbook: cleanup.yaml
