---
- name: Install rdp
  hosts: tag_Name_fresh_install
  become: true
  gather_facts: false

  tasks:
    - name: Install apt packages
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
        pkg:
            - xrdp

    - name: Add the user 'xrdp'
      ansible.builtin.user:
        name: xrdp
        group: ssl-cert
        comment: xrdp

    - name: Restart service xrdp in all cases
      ansible.builtin.service:
        name: xrdp
        state: restarted

    - name: Copy xrdp ini file
      copy:
        src: ./Files/xrdp.ini
        dest:  /etc/xrdp/

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:

